name: publish
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    environment:
      name: Publish
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ">=20.8.1"
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release